### ISSUE TITLE
Review code structure

### ISSUE THREAD

**Issue by tatosweb** [Shinkei/PhaserInit#4]
Review code structure

**Comment by Shinkei** [comment]
I will add eslint and try to modify the code to use the ES6 sintax, and maybe babel if it's needed

**Comment by Shinkei** [comment]
The idea to solve this ticket is to use ES6 additionally give support convert to ES5 with babel and use modules, so the best choice in my opinion would be webpack, so in that case we would need to redo all the code with the new syntax. 
@tatosweb let me know if you want to help with this task otherwise we should stop adding new functionalities until this task ends.

**Comment by tatosweb** [comment]
@Shinkei yes, stop new functionality, and let's refactor the code, then we can continue with new features.

**Comment by tatosweb** [comment]
Change to ES6
